<a href="https://colab.research.google.com/github/LuciaStremel/ingenias/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


1. Crea un arreglo de ceros de longitud 12

In [1]:
import numpy as np
arreglo = np.zeros(12)
print(arreglo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crea un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posicion numero 5

In [3]:
arreglo2 =np.zeros(10)
arreglo2[4] = 10
print(arreglo2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3. Crea un arreglo que tenga los numeros del 10 al 49

In [6]:
arreglo3 = np.arange (10,50)
print(arreglo3)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [11]:
arreglo4 = np.arange (0,9)
arreglo2d = arreglo4.reshape(3,3)
print (arreglo2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza


In [12]:
arreglo5 =np.random.random(100)
media = np.mean(arreglo5)
varianza = np.var(arreglo5)
print (media)
print (varianza)

0.5051587396450742
0.08329635114739328


6. Calcular la media de un arreglo usando np.sum


In [13]:
arreglo6 = np.random.random(50)
media =np.sum(arreglo6)/len(arreglo6)
print (media)

0.4443439824409434


7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [14]:
arreglo7 = np.random.random(100)
media = np.mean(arreglo7)
varianza = np.sum((arreglo7 - media)**2)/len(arreglo7)
print (varianza)

0.07675574216000167


8. Crear un array de números aleatorios usando np.random.randn.

In [15]:
arreglo8 = np.random.rand (15)
print (arreglo8)

[0.85424471 0.79266028 0.16271304 0.89575232 0.12330644 0.20542089
 0.44110213 0.97630947 0.16075247 0.28027718 0.48702707 0.63918096
 0.8082536  0.54310604 0.4662066 ]
